#!/bin/sh -

##
# Default options
DEFAULT_BACKUP_NAME="backup-`hostname`"
DEFAULT_BACKUP_DIR="/var/www"

DEFAULT_COMPRESS_CMD="`which tar`"
DEFAULT_COMPRESS_FLAGS="-czf"
DEFAULT_COMPRESS_SUFFIX=".tar.gz"

DEFAULT_MYSQLDUMP_CMD="`which mysqldump`"
DEFAULT_MYSQLDUMP_FLAGS="--opt --all-databases"
DEFAULT_MYSQLDUMP_SUFFIX=".sql"

DEFAULT_CRYPT_CMD="`which openssl`"
DEFAULT_CRYPT_SUFFIX=".dat"
DEFAULT_CRYPT_FLAGS="enc -aes-256-cbc -e"

DEFAULT_UPLOAD_CMD="`which curl`"
DEFAULT_UPLOAD_URL="https://webdav.yandex.ru/backup/"

help() {
cat <<EOF
usage: ${0} config
       ${0} config1 config2 ... configN
       ${0} *.conf?g

example config:

#   variable          ##  default value
                      #
backup_dir=           # ${DEFAULT_BACKUP_DIR}
backup_name=          # ${DEFAULT_BACKUP_NAME}
                      #
compress_cmd=         # ${DEFAULT_COMPRESS_CMD}
compress_flags=       # ${DEFAULT_COMPRESS_FLAGS}
compress_suffix=      # ${DEFAULT_COMPRESS_SUFFIX}
                      #
mysqldump_cmd=        # ${DEFAULT_MYSQLDUMP_CMD}
mysqldump_flags=      # ${DEFAULT_MYSQLDUMP_FLAGS}
mysqldump_suffix=     # ${DEFAULT_MYSQLDUMP_SUFFIX}
                      #
crypt_cmd=            # ${DEFAULT_CRYPT_CMD}
crypt_suffix=         # ${DEFAULT_CRYPT_SUFFIX}
crypt_password=       # REQURE
crypt_flags=          # ${DEFAULT_CRYPT_FLAGS}
                      #
upload_cmd=           # ${DEFAULT_UPLOAD_CMD}
upload_extra_flags=   # not set
upload_username=      # REQURE
upload_password=      # REQURE
upload_url=           # ${DEFAULT_UPLOAD_URL}
EOF
}

if [ $# -eq 0 ]; then
  help
  exit 1
fi

error=0
for config in "${@}"; do
  if [ -r "${config}" ]; then
    . "${config}"
    if [ -z "${backup_name}" ]; then
      backup_name=${DEFAULT_BACKUP_NAME}
    fi
    if [ -z "${backup_dir}" ]; then
      backup_dir=${DEFAULT_BACKUP_DIR}
    fi
    if [ ! -d "${backup_dir}" ]; then
      echo "Directory ${backup_dir} not exist"
      error=1
    fi

    if [ -z "${mysqldump_cmd}" ]; then
      mysqldump_cmd=${DEFAULT_MYSQLDUMP_CMD}
    fi
    if [ ! -x "${mysqldump_cmd}" ]; then
      echo "File ${mysqldump_cmd} not exist or not execute"
      error=1
    fi
    if [ -z "${mysqldump_flags}" ]; then
      mysqldump_flags=${DEFAULT_MYSQLDUMP_FLAGS}
    fi
    if [ -z "${mysqldump_suffix}" ]; then
      mysqldump_suffix=${DEFAULT_MYSQLDUMP_SUFFIX}
    fi
    if [ -z "${compress_cmd}" ]; then
      compress_cmd=${DEFAULT_COMPRESS_CMD}
    fi
    if [ ! -x "${compress_cmd}" ]; then
      echo "File ${compress_cmd} not exist or not execute"
      error=1
    fi
    if [ -z "${compress_flags}" ]; then
      compress_flags=${DEFAULT_COMPRESS_FLAGS}
    fi
    if [ -z "${compress_suffix}" ]; then
      compress_suffix=${DEFAULT_COMPRESS_SUFFIX}
    fi
    if [ -z "${crypt_cmd}" ]; then
      crypt_cmd=${DEFAULT_CRYPT_CMD}
    fi
    if [ ! -x "${crypt_cmd}" ]; then
      echo "File ${crypt_cmd} not exits or not execute"
      error=1
    fi 
    if [ -z "${crypt_suffix}" ]; then
      crypt_suffix=${DEFAULT_CRYPT_SUFFIX}
    fi
    if [ -z "${crypt_password}" ]; then
      echo "Please enter a password to encrypt files (set variable crypt_password)"
      error=1
    fi
    if [ -z "${crypt_flags}" ]; then
      crypt_flags="enc -aes-256-cbc -e"
    fi
    if [ -z "${upload_cmd}" ]; then
      upload_cmd=${DEFAULT_UPLOAD_CMD}
    fi
    if [ ! -x "${upload_cmd}" ]; then
      echo "File ${upload_cmd} not found or not execute"
      error=1
    fi 
    if [ -z "${upload_username}" ]; then
      echo "Please enter your user name to upload files (set variable upload_username)"
      error=1 
    fi
    if [ -z "${upload_password}" ]; then
      echo "Please enter a password to upload files (set variable uploaf_password)"
      error=1
    fi
    if [ -z "${upload_url}" ]; then
      upload_url=${DEFAULT_UPLOAD_URL}
    fi
    if [ ${error} -eq 1 ]; then
      exit 1
    fi 
    db_dump="${backup_name}${mysqldump_suffix}"
    backup="${backup_name}${compress_suffix}"
    backup_crypt="${backup_name}${crypt_suffix}"
    "${mysqldump_cmd}" ${mysqldump_flags} > "${db_dump}" && \
    "${compress_cmd}" ${compress_flags} "${backup}" "${backup_dir}" "${db_dump}" && \
    "${crypt_cmd}" ${crypt_flags} -in "${backup}" -out "${backup_crypt}" -k "${crypt_password}" && \
    "${upload_cmd}" ${upload_extra_flags} -u"${upload_username}":"${upload_password}" -T "${backup_crypt}" ${upload_url} && \
    rm -f "${backup_crypt}" "${backup}" "${db_dump}"
  else
    echo "File ${config} not exist or not read"
  fi
done
exit 0
