#!/bin/sh

awstats_conf_dir="/etc/awstats"
prerotate_conf="${awstats_conf_dir}/prerotate"

if [ -r "${prerotate_conf}" ]; then
  . "${prerotate_conf}"
fi

awstats_conf_prefix="${awstats_conf_prefix:="awstats."}"
awstats_conf_suffix="${awstats_conf_suffix:=".conf"}"
awstats_updateall="${awstats_updateall:="/var/www/awstats/tools/awstats_updateall.pl"}"
awstats_prog="${awstats_prog:="/var/www/awstats/wwwroot/cgi-bin/awstats.pl"}"
awstats_url_prefix="${awstats_url_prefix:="/cgi-bin/awstats.pl?config="}"
index_html="${index_html:="/var/www/awstats/wwwroot/index.html"}"

test_me() {
  test_dir="${test_dir:="awstats_test"}"
  awstats_conf_dir="${test_dir}"
  [ ! -d "${test_dir}" ] && mkdir -p "${test_dir}"
  for i in `seq 1 10`; do
    test_file="${test_dir}/awstats.examle${i}.com.conf"
    [ ! -f "${test_file}" ] && touch "${test_file}"
  done
}

get_site_names() {
  if [ ! -d "${awstats_conf_dir}" ]; then
    echo "\"${awstats_conf_dir}\" in not directory"
    exit 1
  fi
  ls "${awstats_conf_dir}/${awstats_conf_prefix}"*"${awstats_conf_suffix}" | \
    sed -e "s|${awstats_conf_dir}\/${awstats_conf_prefix}\(.*\)${awstats_conf_suffix}|\1|"
}

update_stats() {
  if [ ! -x "${awstats_updateall}" ]; then
    echo "\"${awstats_updateall}\" not found or not execute"
    exit 1
  fi
  if [ ! -x "${awstats_prog}" ]; then
    echo "\"${awstats_prog}\" not found or not execute"
    exit 1
  fi
  if [ ! -d "${awstats_conf_dir}" ]; then
    echo "\"${awstats_conf_dir}\" in not directory"
    exit 1
  fi
  "${awstats_updateall}" now -awstatsprog="${awstats_prog}" -configdir="${awstats_conf_dir}"
}

#index_html="index.html"
#test_dir="fd/dfs/sdf/"
#test_me

update_stats

touch "${index_html}"
if [ ! -w "${index_html}" ]; then
  echo "file \"${index_html}\" not writable"
  exit 1
fi

# header
cat > "${index_html}" <<EOL
<!doctype html><html><head><title>list sites</title></head><body>
EOL

echo "<ul>" >> "${index_html}"
for site_name in `get_site_names`; do
  echo "<li><a href=\"${awstats_url_prefix}${site_name}\" title=\"Statistics for ${site_name}\">${site_name}</a></li>" >> "${index_html}"
done
echo "</ul>" >> "${index_html}"

# footer
cat >> "${index_html}" <<EOL
</body></html>
EOL
